services:
  app:
    image: gkibria121/laravel:12-node22x_composer
    ports:
      - 8000:8000
    volumes:
      - .:/app   
    entrypoint: /app/bin/entrypoint.sh 
    restart:  unless-stopped

  db:
    image: mariadb:10.5.7
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=apex365
    restart: unless-stopped  # Add restart policy
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    ports:
      - '8080:80'
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=app
    restart: unless-stopped  # Add restart policy