version: 2.1

orbs:
  node: circleci/node@5
  php: circleci/php@1

jobs:
  build:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout

      # Install PHP dependencies
      - php/install-composer
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install PHP dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # Install Node dependencies
      - node/install-packages:
          pkg-manager: npm
          cache-path: node_modules

      # Build assets
      - run:
          command: npm run build

      # Handle artifacts
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: |
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: build-output

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Validate Required Variables
          command: |
            REQUIRED_VARS=("SSH_FINGERPRINT" "SSH_HOST" "SSH_USER" "APP_DIR" "DEPLOY_SCRIPT")
            for VAR in "${REQUIRED_VARS[@]}"; do
              if [ -z "${!VAR}" ]; then
                echo "Error: Missing required environment variable: $VAR"
                exit 1
              fi
            done
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT" # Add this in CircleCI settings
      - run:
          name: Add SSH Host Key
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Pull Latest Changes and Deploy
          command: |
            ssh $SSH_USER@$SSH_HOST "
            cd $APP_DIR &&
            git reset --hard &&
            git fetch &&
            git checkout main &&
            git pull &&
            chmod +x $DEPLOY_SCRIPT &&
            $DEPLOY_SCRIPT &&
            echo 'Deployment completed successfully'"

  deploy-to-staging:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Validate Required Variables
          command: |
            REQUIRED_VARS=("STAGING_SSH_FINGERPRINT" "STAGING_SSH_HOST" "STAGING_SSH_USER" "STAGING_APP_DIR" "STAGING_DEPLOY_SCRIPT")
            for VAR in "${REQUIRED_VARS[@]}"; do
              if [ -z "${!VAR}" ]; then
                echo "Error: Missing required environment variable: $VAR"
                exit 1
              fi
            done
      - add_ssh_keys:
          fingerprints:
            - "$STAGING_SSH_FINGERPRINT"
      - run:
          name: Add SSH Host Key
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $STAGING_SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Pull Latest Changes and Deploy to Staging
          command: |
            ssh $STAGING_SSH_USER@$STAGING_SSH_HOST "
            cd $STAGING_APP_DIR &&
            git reset --hard &&
            git fetch &&
            git checkout staging &&
            git pull &&
            chmod +x $STAGING_DEPLOY_SCRIPT &&
            $STAGING_DEPLOY_SCRIPT &&
            echo 'Staging deployment completed successfully'"

  deploy-to-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Validate Required Variables
          command: |
            REQUIRED_VARS=("DEV_SSH_FINGERPRINT" "DEV_SSH_HOST" "DEV_SSH_USER" "DEV_APP_DIR" "DEV_DEPLOY_SCRIPT")
            for VAR in "${REQUIRED_VARS[@]}"; do
              if [ -z "${!VAR}" ]; then
                echo "Error: Missing required environment variable: $VAR"
                exit 1
              fi
            done
      - add_ssh_keys:
          fingerprints:
            - "$DEV_SSH_FINGERPRINT"
      - run:
          name: Add SSH Host Key
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $DEV_SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Pull Latest Changes and Deploy to Dev
          command: |
            ssh $DEV_SSH_USER@$DEV_SSH_HOST "
            cd $DEV_APP_DIR &&
            git reset --hard &&
            git fetch &&
            git checkout dev &&
            git pull &&
            chmod +x $DEV_DEPLOY_SCRIPT &&
            $DEV_DEPLOY_SCRIPT &&
            echo 'Dev deployment completed successfully'"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - approve-deploy:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - staging
                - main
      - deploy-to-dev:
          requires:
            - build
      - deploy-to-staging:
          requires:
            - build
          filters:
            branches:
              only:
                - staging
      - deploy:
          requires:
            - approve-deploy
          filters:
            branches:
              only:
                - main
