version: 2.1

orbs:
  node: circleci/node@5
  php: circleci/php@1

jobs:
  build:
    docker:
      - image: cimg/php:8.2-node
    steps:
      - checkout

      # Install PHP dependencies
      - php/install-composer
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install PHP dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

      # Install Node dependencies
      - node/install-packages:
          pkg-manager: npm
          cache-path: node_modules

      # Build assets
      - run:
          command: npm run build

      # Handle artifacts
      - run:
          name: Create artifacts directory
          command: mkdir -p ~/artifacts
      - run:
          name: Copy artifacts
          command: |
            cp -R build dist public .output .next .docusaurus ~/artifacts 2>/dev/null || true
      - store_artifacts:
          path: ~/artifacts
          destination: build-output

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT" # Add this in CircleCI settings
      - run:
          name: Add SSH Host Key
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - run:
          name: Pull Latest Changes and Deploy
          command: |
            ssh $SSH_USER@$SSH_HOST "
            cd /var/www/apex365 &&
            git fetch
            git pull &&
            chmod +x ./bin/deploy_prod.sh &&
            ./bin/deploy_prod.sh &&
            echo 'Deployment completed successfully'"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - approve-deploy:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - approve-deploy
          filters:
            branches:
              only:
                - main
